version: '3'
services:
  firestore:
    container_name: firestore
    image: google/cloud-sdk:425.0.0
    ports:
      - "8342:8342"
    command:
      "gcloud beta emulators firestore start --project=my-project-id --host-port 0.0.0.0:8342"